name: Bug Report
description: Create a report to help us improve FYAML
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the following information to help us resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: Please provide a minimal, complete, and verifiable example
      render: fortran
      placeholder: |
        program minimal_example
            use fyaml
            implicit none

            ! Your code that demonstrates the issue

        end program
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Ubuntu/Debian
        - CentOS/RHEL/Fedora
        - macOS
        - Windows
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: compiler
    attributes:
      label: Compiler
      description: What Fortran compiler are you using?
      placeholder: e.g., gfortran 11.2, ifort 2021.4
    validations:
      required: true

  - type: input
    id: fyaml-version
    attributes:
      label: FYAML Version
      description: What version of FYAML are you using?
      placeholder: e.g., v0.2.0, commit hash
    validations:
      required: true

  - type: input
    id: cmake-version
    attributes:
      label: CMake Version
      description: What version of CMake are you using?
      placeholder: e.g., 3.20.0
    validations:
      required: false

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Any error messages or compiler output
      render: shell
      placeholder: Paste any error messages or compiler output here
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a minimal, complete, and verifiable example (if applicable)
          required: false
        - label: I have included all relevant environment information
          required: true
        - label: I have checked that this issue occurs with the latest version of FYAML
          required: true
