count_leading_spaces – Fyaml
count_leading_spaces Function
10 statements
Source File
public function count_leading_spaces(line)
Count leading spaces in a string
Used for determining indentation level
@param[in] line Input string @return Number of leading spaces
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: line
Return Value integer
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: i
Call graph
find_sequence_parent calls count_leading_spaces
find_sequence_parent_node calls count_leading_spaces
has_sequence_parent calls count_leading_spaces
parse_line calls count_leading_spaces
handle_block_sequence calls find_sequence_parent_node
parse_yaml_wrapper calls parse_line
parse_yaml calls parse_yaml_wrapper