debug_print – Fyaml
debug_print Subroutine
34 statements
Source File
public subroutine debug_print(level, message, error_code, msg_type)
Print debug messages with appropriate formatting and prefixes
@param[in] level Debug level of the message @param[in] message The debug message to print @param[in] error_code Optional error code associated with the message @param[in] msg_type Optional message type for prefix selection
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
character(len=*), intent(in) :: message
integer, intent(in), optional :: error_code
character(len=*), intent(in), optional :: msg_type
Called by
Variables
Type Visibility Attributes Name Initial
character(len=:), public, allocatable :: formatted_msg
character(len=:), public, allocatable :: prefix
Call graph
check_key_hierarchy calls debug_print
debug_print_node_structure calls debug_print, debug_print_node_structure
find_block_sequence_parent calls debug_print
find_parent_by_indent calls debug_print
find_sequence_parent_node calls debug_print
get_sequence_as_strings calls debug_print
parse_flow_form calls debug_print
parse_line calls debug_print, find_block_sequence_parent, find_parent_by_indent, parse_flow_form
parse_yaml_wrapper calls debug_print, parse_line
validate_node calls debug_print
parse_yaml calls parse_yaml_wrapper
handle_block_sequence calls find_sequence_parent_node