initialize_node – Fyaml
initialize_node Subroutine
13 statements
Source File
public subroutine initialize_node(node)
Initialize a new YAML node
Sets default values for a newly created node
@param[in,out] node Node to initialize
Arguments
Type Intent Optional Attributes Name
type(yaml_node), intent(inout), pointer :: node
Called by
Call graph
add_sequence_item calls initialize_node
find_or_create_intermediate_nodes calls initialize_node
parse_line calls initialize_node, parse_flow_form
parse_mapping calls initialize_node
parse_flow_form calls add_sequence_item
parse_yaml_wrapper calls parse_line
parse_yaml calls parse_yaml_wrapper