parse_line – Fyaml
parse_line Subroutine
216 statements
Source File
public subroutine parse_line(line, doc, status, line_num)
Parse a single line of YAML content
Processes a line and updates document structure. Handles: - Indentation - Sequence items - Key-value pairs - Nested structures
@param[in] line Input line @param[in,out] doc Document being built @param[out] status Status code @param[in] line_num Line number of the input line
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: line
type(yaml_document), intent(inout) :: doc
integer, intent(out) :: status
integer, intent(in) :: line_num
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: current_indent
type(yaml_node), public, pointer :: current_node
character(len=256), public :: debug_msg
character(len=256), public :: error_msg
integer, public :: io_stat
logical, public :: is_sequence_item
character(len=:), public, allocatable :: local_line
type(yaml_node), public, pointer :: new_node
integer, public :: parent_indent
character(len=:), public, allocatable :: parent_key
type(yaml_node), public, pointer :: parent_node
integer, public :: pos
Call graph
parse_line calls count_leading_spaces, debug_print, find_block_sequence_parent, find_parent_by_indent, initialize_node, integer_to_string, parse_flow_form, record_indent_level
find_block_sequence_parent calls debug_print
find_parent_by_indent calls debug_print
parse_flow_form calls debug_print, add_sequence_item
add_sequence_item calls initialize_node
parse_yaml_wrapper calls parse_line
parse_yaml calls parse_yaml_wrapper