parse_flow_form – Fyaml
parse_flow_form Subroutine
36 statements
Source File
public subroutine parse_flow_form(line, node)
Parse flow-style YAML syntax
Handles flow-style sequences [...] and mappings {...}
@param[in] line Input containing flow syntax @param[inout] node Node to store parsed content
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: line
type(yaml_node), intent(inout), pointer :: node
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=:), public, allocatable :: content
type(yaml_node), public, pointer :: current_item
integer, public :: end
logical, public :: in_bracket
logical, public :: in_quotes
character(len=:), public, allocatable :: item
integer, public :: item_end
integer, public :: item_start
integer, public :: pos
type(yaml_node), public, pointer :: prev_item
integer, public :: start
Call graph
parse_flow_form calls add_sequence_item, debug_print
add_sequence_item calls initialize_node
parse_line calls parse_flow_form
parse_yaml_wrapper calls parse_line
parse_yaml calls parse_yaml_wrapper