parse_yaml – Fyaml
parse_yaml Subroutine
113 statements
Source File
public subroutine parse_yaml(filename, docs, status)
Uses
yaml_types
iso_fortran_env
Parse a YAML file into document structure
Reads and parses a YAML file into one or more documents
@param[in] filename Path to YAML file @param[out] docs Array of parsed YAML documents @param[out] status Status code (ERR_SUCCESS on success)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(yaml_document), intent(out), allocatable :: docs(:)
integer, intent(out) :: status
Calls
Variables
Type Visibility Attributes Name Initial
character(len=32), public :: cnt_str
integer, public :: doc_count
logical, public :: doc_started
character(len=256), public :: error_msg
integer, public :: i
logical, public :: in_document
integer, public :: io_stat
character(len=1024), public :: line
integer, public :: line_count
integer, public :: unit_num
Call graph
parse_yaml calls debug_print, initialize_document, parse_line, starts_with_trimmed
parse_line calls debug_print, count_leading_spaces, initialize_node