parse_yaml_wrapper – Fyaml
parse_yaml_wrapper Subroutine
16 statements
Source File
public subroutine parse_yaml_wrapper(filename, docs, status)
Wrapper subroutine for parsing YAML files
@param[in] filename Name of the YAML file to parse @param[out] docs Array of parsed YAML documents @param[out] status Status code indicating success or error
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(yaml_document), intent(out), allocatable :: docs(:)
integer, intent(out) :: status
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: doc_count
logical, public :: found_doc_marker
Call graph
parse_yaml_wrapper calls cleanup_indent_history, count_documents, debug_print, initialize_document, integer_to_string, parse_line, starts_with_trimmed
parse_line calls debug_print, integer_to_string, count_leading_spaces, find_block_sequence_parent, find_parent_by_indent, initialize_node, parse_flow_form, record_indent_level
find_block_sequence_parent calls debug_print
find_parent_by_indent calls debug_print
parse_flow_form calls debug_print, add_sequence_item
add_sequence_item calls initialize_node
parse_yaml calls parse_yaml_wrapper