name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        gcc_version: [10, 11, 12, 13]
    env:
      BUILD_DIR: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: fortran-lang/setup-fortran@v1
        name: Setup Fortran
        with:
          compiler: gcc
          version: ${{ matrix.gcc_version }}

      - name: Configure
        run: cmake -S . -B $BUILD_DIR

      - name: Build
        run: cmake --build $BUILD_DIR

      - name: Test
        run: ctest --test-dir $BUILD_DIR/tests/ --output-on-failure
        env:
          FYAML_TEST_DATA_DIR: ${{ github.workspace }}/test_data

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: pre-commit/action@v3.0.1
